version: '3.7'

services:

  btalert-ai:
    container_name: btalert-ai
    build:
      context: .
      dockerfile: dockerfile.python
    ports:
      - 5050:5050
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network
