FROM python:3.7.11
WORKDIR /usr/src/btalert-ai

COPY . .
RUN bash setup-env.sh docker
RUN pip install -r requirements.txt

WORKDIR /usr/src/btalert-ai/src
CMD ["gunicorn", "--bind", "0.0.0.0:5050", "app:app"]