name: Python Conda CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    services:
      mariadb:
        image: mariadb:10.3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: btalert
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.11

      - name: Set up env
        run: |
          bash env.sh prod
          mysql --host 127.0.0.1 --port 3306 -uroot btalert < ./src/resources/ddl-database.sql

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          conda config --add channels conda-forge
          conda install --file requirements.txt --yes

      - name: Lint with flake8
        run: |
          conda install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          conda install pytest
          pytest ./src/tests/*
